'use client';

import type { PanelType } from '@/lib/tiling-types';
import QuoteMonitor from '@/components/panels/quote-monitor';
import SecurityDescription from '@/components/panels/security-description';
import ChartPanel from '@/components/panels/chart-panel';
import NewsFeed from '@/components/panels/news-feed';
import FundamentalsPanel from '@/components/panels/fundamentals-panel';
import PortfolioPanel from '@/components/panels/portfolio-panel';
import FxRatesPanel from '@/components/panels/fx-rates-panel';
import CommodityPanel from '@/components/panels/commodity-panel';
import OptionsChainPanel from '@/components/panels/options-chain-panel';
import EconomicCalendarPanel from '@/components/panels/economic-calendar-panel';
import EarningsPanel from '@/components/panels/earnings-panel';
import AnalystRatingsPanel from '@/components/panels/analyst-ratings-panel';
import BondYieldsPanel from '@/components/panels/bond-yields-panel';
import MarketHeatmapPanel from '@/components/panels/market-heatmap-panel';
import StockScreenerPanel from '@/components/panels/stock-screener-panel';
import InsiderActivityPanel from '@/components/panels/insider-activity-panel';
import InstitutionalHoldingsPanel from '@/components/panels/institutional-holdings-panel';
import SecFilingsPanel from '@/components/panels/sec-filings-panel';
import WorldMarketsPanel from '@/components/panels/world-markets-panel';
import CorrelationRiskPanel from '@/components/panels/correlation-risk-panel';
import SocialSentimentPanel from '@/components/panels/social-sentiment-panel';
import HelpPanel from '@/components/panels/help-panel';
import BrainChatPanel from '@/components/panels/brain-chat-panel';
import BrainSettingsPanel from '@/components/panels/brain-settings-panel';
import FinanceResearchPanel from '@/components/panels/finance-research-panel';
import TickerCardsPanel from '@/components/panels/ticker-cards-panel';
import FearGreedPanel from '@/components/panels/fear-greed-panel';
import MarketBreadthPanel from '@/components/panels/market-breadth-panel';
import TapePanel from '@/components/panels/tape-panel';
import DepthPanel from '@/components/panels/depth-panel';
import UnusualOptionsPanel from '@/components/panels/unusual-options-panel';
import GammaExposurePanel from '@/components/panels/gamma-exposure-panel';
import CongressTradesPanel from '@/components/panels/congress-trades-panel';
import SeasonalityPanel from '@/components/panels/seasonality-panel';
import SectorRotationPanel from '@/components/panels/sector-rotation-panel';
import MoversPanel from '@/components/panels/movers-panel';
import WsbTrendingPanel from '@/components/panels/wsb-trending-panel';
import VixTermPanel from '@/components/panels/vix-term-panel';
import DividendCalendarPanel from '@/components/panels/dividend-calendar-panel';
import BacktestPanel from '@/components/panels/backtest-panel';
import NotesPanel from '@/components/panels/notes-panel';
import SuperInvestorPanel from '@/components/panels/superinvestor-panel';
import EtfFlowsPanel from '@/components/panels/etf-flows-panel';
import AllqPanel from '@/components/panels/allq-panel';
import FinancialAnalysisPanel from '@/components/panels/financial-analysis-panel';
import RatioAnalysisPanel from '@/components/panels/ratio-analysis-panel';
import EarningsMatrixPanel from '@/components/panels/earnings-matrix-panel';
import TranscriptsPanel from '@/components/panels/transcripts-panel';
import MarketHaltsPanel from '@/components/panels/market-halts-panel';
import IpoMonitorPanel from '@/components/panels/ipo-monitor-panel';
import DividendAnalyticsPanel from '@/components/panels/dividend-analytics-panel';
import ResearchNotesPanel from '@/components/panels/research-notes-panel';
import WorkspaceManagerPanel from '@/components/panels/workspace-manager-panel';
import OptionsValuationPanel from '@/components/panels/options-valuation-panel';
import AumPanel from '@/components/panels/aum-panel';
import FinancialCalculatorPanel from '@/components/panels/financial-calculator-panel';

export default function PanelContent({ panelType, panelId }: { panelType: PanelType; panelId: string }) {
  switch (panelType) {
    case 'quote-monitor': return <QuoteMonitor panelId={panelId} />;
    case 'security-description': return <SecurityDescription panelId={panelId} />;
    case 'chart': return <ChartPanel panelId={panelId} />;
    case 'news': return <NewsFeed panelId={panelId} />;
    case 'fundamentals': return <FundamentalsPanel panelId={panelId} />;
    case 'portfolio': return <PortfolioPanel panelId={panelId} />;
    case 'fx-rates': return <FxRatesPanel panelId={panelId} />;
    case 'commodity': return <CommodityPanel panelId={panelId} />;
    case 'options-chain': return <OptionsChainPanel panelId={panelId} />;
    case 'economic-calendar': return <EconomicCalendarPanel panelId={panelId} />;
    case 'earnings': return <EarningsPanel panelId={panelId} />;
    case 'analyst-ratings': return <AnalystRatingsPanel panelId={panelId} />;
    case 'bond-yields': return <BondYieldsPanel panelId={panelId} />;
    case 'market-heatmap': return <MarketHeatmapPanel panelId={panelId} />;
    case 'stock-screener': return <StockScreenerPanel panelId={panelId} />;
    case 'insider-activity': return <InsiderActivityPanel panelId={panelId} />;
    case 'institutional-holdings': return <InstitutionalHoldingsPanel panelId={panelId} />;
    case 'sec-filings': return <SecFilingsPanel panelId={panelId} />;
    case 'world-markets': return <WorldMarketsPanel panelId={panelId} />;
    case 'correlation-risk': return <CorrelationRiskPanel panelId={panelId} />;
    case 'social-sentiment': return <SocialSentimentPanel panelId={panelId} />;
    case 'help': return <HelpPanel panelId={panelId} />;
    case 'brain-chat': return <BrainChatPanel panelId={panelId} />;
    case 'brain-settings': return <BrainSettingsPanel panelId={panelId} />;
    case 'finance-research': return <FinanceResearchPanel panelId={panelId} />;
    case 'ticker-cards': return <TickerCardsPanel panelId={panelId} />;
    case 'fear-greed': return <FearGreedPanel panelId={panelId} />;
    case 'market-breadth': return <MarketBreadthPanel panelId={panelId} />;
    case 'tape': return <TapePanel panelId={panelId} />;
    case 'depth': return <DepthPanel panelId={panelId} />;
    case 'unusual-options': return <UnusualOptionsPanel panelId={panelId} />;
    case 'gamma-exposure': return <GammaExposurePanel panelId={panelId} />;
    case 'congress-trades': return <CongressTradesPanel panelId={panelId} />;
    case 'seasonality': return <SeasonalityPanel panelId={panelId} />;
    case 'sector-rotation': return <SectorRotationPanel panelId={panelId} />;
    case 'movers': return <MoversPanel panelId={panelId} />;
    case 'wsb-trending': return <WsbTrendingPanel panelId={panelId} />;
    case 'vix-term': return <VixTermPanel panelId={panelId} />;
    case 'dividend-calendar': return <DividendCalendarPanel panelId={panelId} />;
    case 'backtest': return <BacktestPanel panelId={panelId} />;
    case 'notes': return <NotesPanel panelId={panelId} />;
    case 'superinvestor': return <SuperInvestorPanel panelId={panelId} />;
    case 'etf-flows': return <EtfFlowsPanel panelId={panelId} />;
    case 'allq': return <AllqPanel panelId={panelId} />;
    case 'financial-analysis': return <FinancialAnalysisPanel panelId={panelId} />;
    case 'ratio-analysis': return <RatioAnalysisPanel panelId={panelId} />;
    case 'earnings-matrix': return <EarningsMatrixPanel panelId={panelId} />;
    case 'transcripts': return <TranscriptsPanel panelId={panelId} />;
    case 'market-halts': return <MarketHaltsPanel panelId={panelId} />;
    case 'ipo-monitor': return <IpoMonitorPanel panelId={panelId} />;
    case 'dividend-analytics': return <DividendAnalyticsPanel panelId={panelId} />;
    case 'research-notes': return <ResearchNotesPanel panelId={panelId} />;
    case 'workspace-manager': return <WorkspaceManagerPanel panelId={panelId} />;
    case 'options-valuation': return <OptionsValuationPanel panelId={panelId} />;
    case 'aum': return <AumPanel panelId={panelId} />;
    case 'financial-calculator': return <FinancialCalculatorPanel panelId={panelId} />;
  }
}
